<?php

namespace Database\Seeders;

use App\Models\Stock;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StockTecnoServiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $materiales = [
            // Routers Wi-Fi
            [
                'codigo' => 'RTR-001',
                'nombre' => 'Router Wi-Fi AC1200',
                'descripcion' => 'Router inalámbrico de doble banda con velocidad de hasta 1200 Mbps',
                'categoria' => 'routers',
                'marca' => 'TP-Link',
                'modelo' => 'Archer C54',
                'cantidad_actual' => 25,
                'cantidad_minima' => 5,
                'cantidad_maxima' => 50,
                'precio_compra' => 45.00,
                'precio_venta' => 75.00,
                'ubicacion' => 'Estante A-1',
                'proveedor' => 'Distribuidora TecnoServi',
                'activo' => true,
            ],
            [
                'codigo' => 'RTR-002',
                'nombre' => 'Router Wi-Fi AX1800',
                'descripcion' => 'Router Wi-Fi 6 con velocidad de hasta 1800 Mbps y tecnología Mesh',
                'categoria' => 'routers',
                'marca' => 'Mercusys',
                'modelo' => 'MR80X',
                'cantidad_actual' => 15,
                'cantidad_minima' => 3,
                'cantidad_maxima' => 30,
                'precio_compra' => 65.00,
                'precio_venta' => 110.00,
                'ubicacion' => 'Estante A-2',
                'proveedor' => 'Distribuidora TecnoServi',
                'activo' => true,
            ],

            // Módems
            [
                'codigo' => 'MDM-001',
                'nombre' => 'Módem DOCSIS 3.0',
                'descripcion' => 'Módem cable de alta velocidad compatible con DOCSIS 3.0',
                'categoria' => 'modems',
                'marca' => 'Motorola',
                'modelo' => 'MB7420',
                'cantidad_actual' => 20,
                'cantidad_minima' => 4,
                'cantidad_maxima' => 40,
                'precio_compra' => 55.00,
                'precio_venta' => 95.00,
                'ubicacion' => 'Estante B-1',
                'proveedor' => 'Proveedor CableVisión',
                'activo' => true,
            ],
            [
                'codigo' => 'MDM-002',
                'nombre' => 'Módem Wi-Fi Integrado',
                'descripcion' => 'Módem con router Wi-Fi integrado de 300 Mbps',
                'categoria' => 'modems',
                'marca' => 'Netgear',
                'modelo' => 'CM400',
                'cantidad_actual' => 12,
                'cantidad_minima' => 3,
                'cantidad_maxima' => 25,
                'precio_compra' => 70.00,
                'precio_venta' => 120.00,
                'ubicacion' => 'Estante B-2',
                'proveedor' => 'Proveedor CableVisión',
                'activo' => true,
            ],

            // Cables
            [
                'codigo' => 'CAB-001',
                'nombre' => 'Cable Coaxial RG6',
                'descripcion' => 'Cable coaxial blindado para instalaciones de TV por cable - 100m',
                'categoria' => 'cables',
                'marca' => 'Belden',
                'modelo' => 'RG6-100M',
                'cantidad_actual' => 50,
                'cantidad_minima' => 10,
                'cantidad_maxima' => 100,
                'precio_compra' => 25.00,
                'precio_venta' => 45.00,
                'ubicacion' => 'Estante C-1',
                'proveedor' => 'Ferretería El Cable',
                'activo' => true,
            ],
            [
                'codigo' => 'CAB-002',
                'nombre' => 'Cable UTP Cat6',
                'descripcion' => 'Cable de red UTP Categoría 6 para conexiones Ethernet - 50m',
                'categoria' => 'cables',
                'marca' => 'D-Link',
                'modelo' => 'CAT6-50M',
                'cantidad_actual' => 30,
                'cantidad_minima' => 8,
                'cantidad_maxima' => 60,
                'precio_compra' => 15.00,
                'precio_venta' => 28.00,
                'ubicacion' => 'Estante C-2',
                'proveedor' => 'Ferretería El Cable',
                'activo' => true,
            ],

            // Precintos y Sujetadores
            [
                'codigo' => 'PRC-001',
                'nombre' => 'Precinto Plástico 4.8mm x 200mm',
                'descripcion' => 'Precintos plásticos de seguridad para conexiones - Paquete x100',
                'categoria' => 'precintos',
                'marca' => 'Thomas & Betts',
                'modelo' => 'Ty-Rap 200mm',
                'cantidad_actual' => 80,
                'cantidad_minima' => 15,
                'cantidad_maxima' => 200,
                'precio_compra' => 8.50,
                'precio_venta' => 15.00,
                'ubicacion' => 'Estante D-1',
                'proveedor' => 'Distribuidora Industrial',
                'activo' => true,
            ],
            [
                'codigo' => 'PRC-002',
                'nombre' => 'Precinto Metálico 4.8mm x 300mm',
                'descripcion' => 'Precintos metálicos de alta resistencia - Paquete x50',
                'categoria' => 'precintos',
                'marca' => 'Panduit',
                'modelo' => 'Ball-Lock 300mm',
                'cantidad_actual' => 60,
                'cantidad_minima' => 12,
                'cantidad_maxima' => 150,
                'precio_compra' => 12.00,
                'precio_venta' => 22.00,
                'ubicacion' => 'Estante D-2',
                'proveedor' => 'Distribuidora Industrial',
                'activo' => true,
            ],

            // Tarugos
            [
                'codigo' => 'TAR-001',
                'nombre' => 'Tarugo Nylon 6mm',
                'descripcion' => 'Tarugos de expansión para fijación en pared - Paquete x100',
                'categoria' => 'conectores',
                'marca' => 'Fischer',
                'modelo' => 'SX6',
                'cantidad_actual' => 120,
                'cantidad_minima' => 20,
                'cantidad_maxima' => 300,
                'precio_compra' => 6.00,
                'precio_venta' => 12.00,
                'ubicacion' => 'Estante E-1',
                'proveedor' => 'Ferretería La Construcción',
                'activo' => true,
            ],
            [
                'codigo' => 'TAR-002',
                'nombre' => 'Tarugo Nylon 8mm',
                'descripcion' => 'Tarugos de expansión para fijación en pared - Paquete x100',
                'categoria' => 'conectores',
                'marca' => 'Fischer',
                'modelo' => 'SX8',
                'cantidad_actual' => 100,
                'cantidad_minima' => 18,
                'cantidad_maxima' => 250,
                'precio_compra' => 8.00,
                'precio_venta' => 16.00,
                'ubicacion' => 'Estante E-2',
                'proveedor' => 'Ferretería La Construcción',
                'activo' => true,
            ],

            // Grampas
            [
                'codigo' => 'GRA-001',
                'nombre' => 'Grampa para Cable Coaxial',
                'descripcion' => 'Grampas plásticas para sujeción de cables coaxiales - Paquete x50',
                'categoria' => 'grampas',
                'marca' => 'Ideal',
                'modelo' => 'Coax Clip',
                'cantidad_actual' => 150,
                'cantidad_minima' => 25,
                'cantidad_maxima' => 400,
                'precio_compra' => 4.50,
                'precio_venta' => 9.00,
                'ubicacion' => 'Estante F-1',
                'proveedor' => 'Ferretería El Cable',
                'activo' => true,
            ],
            [
                'codigo' => 'GRA-002',
                'nombre' => 'Grampa para Cable UTP',
                'descripcion' => 'Grampas plásticas para sujeción de cables UTP - Paquete x50',
                'categoria' => 'grampas',
                'marca' => 'Leviton',
                'modelo' => 'UTP Clip',
                'cantidad_actual' => 120,
                'cantidad_minima' => 20,
                'cantidad_maxima' => 300,
                'precio_compra' => 5.00,
                'precio_venta' => 10.00,
                'ubicacion' => 'Estante F-2',
                'proveedor' => 'Ferretería El Cable',
                'activo' => true,
            ],

            // Cajas de Conexión
            [
                'codigo' => 'CAJ-001',
                'nombre' => 'Caja de Conexión Exterior',
                'descripcion' => 'Caja de conexión a prueba de agua para instalaciones exteriores',
                'categoria' => 'cajas',
                'marca' => 'Legrand',
                'modelo' => 'Exterior Box 200',
                'cantidad_actual' => 35,
                'cantidad_minima' => 7,
                'cantidad_maxima' => 70,
                'precio_compra' => 18.00,
                'precio_venta' => 32.00,
                'ubicacion' => 'Estante G-1',
                'proveedor' => 'Distribuidora Eléctrica',
                'activo' => true,
            ],
            [
                'codigo' => 'CAJ-002',
                'nombre' => 'Caja de Conexión Interior',
                'descripcion' => 'Caja de conexión para instalaciones interiores con tapa',
                'categoria' => 'cajas',
                'marca' => 'Siemens',
                'modelo' => 'Interior Box 150',
                'cantidad_actual' => 40,
                'cantidad_minima' => 8,
                'cantidad_maxima' => 80,
                'precio_compra' => 12.00,
                'precio_venta' => 22.00,
                'ubicacion' => 'Estante G-2',
                'proveedor' => 'Distribuidora Eléctrica',
                'activo' => true,
            ],

            // Herramientas
            [
                'codigo' => 'HERR-001',
                'nombre' => 'Kit de Herramientas Instalador',
                'descripcion' => 'Kit completo de herramientas para instalación de cable y conectores',
                'categoria' => 'herramientas',
                'marca' => 'Klein Tools',
                'modelo' => 'Cable Installer Kit',
                'cantidad_actual' => 8,
                'cantidad_minima' => 2,
                'cantidad_maxima' => 15,
                'precio_compra' => 85.00,
                'precio_venta' => 150.00,
                'ubicacion' => 'Estante H-1',
                'proveedor' => 'Herramientas Profesionales',
                'activo' => true,
            ],
            [
                'codigo' => 'HERR-002',
                'nombre' => 'Pelacables Profesional',
                'descripcion' => 'Pelacables automático para cables coaxiales y UTP',
                'categoria' => 'herramientas',
                'marca' => 'Jonard Tools',
                'modelo' => 'Cable Stripper Pro',
                'cantidad_actual' => 12,
                'cantidad_minima' => 3,
                'cantidad_maxima' => 25,
                'precio_compra' => 35.00,
                'precio_venta' => 65.00,
                'ubicacion' => 'Estante H-2',
                'proveedor' => 'Herramientas Profesionales',
                'activo' => true,
            ],
        ];

        foreach ($materiales as $material) {
            Stock::create($material);
        }

        $this->command->info('Se han creado ' . count($materiales) . ' productos en el stock de TecnoServi');
    }
}

